name: Backend Tests
on:
  push:
    branches:
      - team3-nikesh
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm install
      run: npm run migrate
      run: npm run dev
      run: npm run test:integration
      run: npm run test:unit
      
      








