name: E2E Tests After Frontend Deployment

on:
  workflow_run:
    workflows: ["Frontend Tests"]
    types:
      - completed
    branches: [ team3-nikesh ] 

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './e2e-tests/package-lock.json'
    
    - name: Install Cypress dependencies
      working-directory: ./e2e-tests
      run: npm install
    
    - name: Run Cypress E2E Tests
      working-directory: ./e2e-tests
      run: npx cypress run
      env:
        CYPRESS_BASE_URL: ${{ secrets.FRONTEND_URL }}
        CYPRESS_API_URL: ${{ secrets.REACT_APP_API_URL }}
    
    - name: Upload Cypress screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: e2e-tests/cypress/screenshots
        if-no-files-found: ignore
    
    - name: Upload Cypress videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: e2e-tests/cypress/videos
        if-no-files-found: ignore 