name: Frontend Tests
on:
  push:
    branches:
      - team3-nikesh
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Run Frontend Tests
      run: |
        chmod +x ./scripts/test-frontend.sh
        ./scripts/test-frontend.sh








